### PR TITLE
Integrating travis into CML-flogo for running all tests before merge time

### PR DESCRIPTION
**Pull request by abramvandergeest**
Sorry for all the commits, I was working a lot of debugging (first debugging travis, then debugging the test fails in cmlf).  Biggest problem was references in go.mods where to cmlf master repo, when it need to be the repo we were pushing.  But finally everything came back green.

### CODE REVIEW

**Review by skothari-tibco — APPROVED** [review]

**Comment by mellistibco** [comment]
Do we still need the replace's in the go.mods for the operations? We should also look at tagging the operations... @fm-tibco thoughts?

**Comment by abramvandergeest** [comment]
Yes, we need the replaces, because even with tags you are using a version other than the one you are checking in which defeats the point of 1)tests and 2)building it as one tool set

**Comment by mellistibco** [comment]
I'm really not sure this will work with `go get -u` when `GO111MODULE` is set to on... I think we need to tag operations and and just update the go.mod tags when appropriate.

See the snippet below. `go get` will fetch all of the operations into the specific version. I'm sure the replace ../operations/common, etc isn't going to work since ../operations/common, etc doesn't actually exist...

```
pwd
/Users/mellis/go/pkg/mod/github.com/project-flogo/catalystml-flogo
mellis@Matts-MacBook-Pro-5 catalystml-flogo % ls
action@v0.0.0-20200218153131-0a290fa79171	operations
mellis@Matts-MacBook-Pro-5 catalystml-flogo % cd operations
mellis@Matts-MacBook-Pro-5 operations % ls
cleaning@v0.0.0-20191221100507-49a2889fd614		image_processing@v0.1.6					restructuring@v0.0.0-20200218153131-0a290fa79171
cleaning@v0.0.0-20200218153131-0a290fa79171		math@v0.0.0-20191221100507-49a2889fd614			string_processing@v0.0.0-20191221100507-49a2889fd614
common@v0.0.0-20191221100507-49a2889fd614		math@v0.0.0-20200218153131-0a290fa79171			string_processing@v0.0.0-20200218153131-0a290fa79171
common@v0.0.0-20200218153131-0a290fa79171		nlp@v0.0.0-20200218153131-0a290fa79171
image_processing@v0.0.0-20191221100507-49a2889fd614	restructuring@v0.0.0-20191221100507-49a2889fd614
```

**Comment by abramvandergeest** [comment]
I am okay with tagging the operation category versions, and if that fixes it that is great, the problem was there was no version in the main repo with the correct directory name so with out doing another PR (which for a number of reasons I was not in a position to do) to fix that before I finished this we were stuck with a chicken and an egg

**Comment by skothari-tibco** [comment]
@mellistibco I agree we can tag each operations and use those instead of replace. However replace is only valid for the examples repo and test cases in the action repo. Those would not come up when you build/run the app.
Edit: My bad., I just checked the replaces in my repo 😅

**Comment by abramvandergeest** [comment]
@skothari-tibco - @mellistibco is more referring to the replace statements I put into action and operations/utils to get travis to finish correctly

**Review by mellistibco — APPROVED** [review]

**Comment by abramvandergeest** [comment]
I am going to merge this PR.  Tag the category with a new version.  Then I am going to create another PR with the travis file included.

**Pull request merged**
