### PR TITLE
Add rum_cml

### PR DESCRIPTION
**Pull request by skothari-tibco**
#69

### CODE REVIEW

**Review by abramvandergeest — CHANGES_REQUESTED** [review]
Seems good.  But can we change the sample json to something with actual operations in it?  Maybe something from the common_strucs/ dir in the cml repo

**Comment by skothari-tibco** [comment]
Sure.

**Comment by abramvandergeest** [comment]
have we done this yet?

**Comment by skothari-tibco** [comment]
Just did.

**Review by abramvandergeest — APPROVED** [review]
Looks good.  I assume you have tested it.

**Pull request merged**
