### PR TITLE
Merge Matrix Ops and Merge Operations import.

### PR DESCRIPTION
**Pull request by skothari-tibco**
Also takes care of #102

### CODE REVIEW

**Comment by skothari-tibco** [comment]
I would like to run all the tests again, to make sure this works and there's no error.

**Comment by abramvandergeest** [comment]
it looks good aside from this question.  Can we define a variable for the function so we don't have to have the heave switch statement 3 times with the only diff as the function?

**Comment by abramvandergeest** [comment]
LGTM

**Review by abramvandergeest — APPROVED** [review]
LGTM

**Comment by skothari-tibco** [comment]
@abramvandergeest . We can merge this . Can you just review it once again ?

**Review by abramvandergeest — APPROVED** [review]
LGTM

**Pull request merged**
