### PR TITLE
Update operations

### PR DESCRIPTION
**Pull request by skothari-tibco**

### CODE REVIEW

**Review by abramvandergeest — COMMENTED** [review]
Does it make sense to move ToArray to common? it is in at least two places

**Comment by skothari-tibco** [comment]
I'm not sure it's something that it would be used by other people. And I would also advise against it. Those two instances are same, but they service that particular operation's requirements. Also one thing I forgot to add in comments is that, the reason I'm removing "coerce.ToArray" is because there is change in that code and it breaks our implementation.

**Review by abramvandergeest — APPROVED** [review]
Thanks! LGTM

**Review by abramvandergeest — APPROVED** [review]
lgtm

**Pull request merged**
